add_friend/urls.py
from django.conf.urls import url
from .views import index, add_friend
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    ]

add_profile/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

add_stats/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='stats'),
	]

add_updatestatus/urls.py
from django.conf.urls import url
from .views import index, update_status

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^update_status', update_status, name='update_status'),
]

tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import add_profile.urls as profile
import add_friend.urls as add_friend
import add_stats.urls as stats
import add_updatestatus.urls as updatestatus
from add_friend.views import index as index_status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^profile/', include(profile, namespace="profile")),
    url(r'^add-friend/', include(add_friend, namespace="add-friend")),
    url(r'^stats/', include(stats, namespace="statistic")),
    url(r'^update-status/', include(updatestatus, namespace="update-status")),
    url(r'^$', index_status, name='index')
]

add_friend/models.py
from django.db import models

class Friend(models.Model):
    Name = models.CharField(max_length=27)
    URL = models.URLField()
    created_date = models.DateTimeField(auto_now_add=True)

add_profile/models.py
from django.db import models

# Create your models here.
class Identity(models.Model):
    name = models.CharField(max_length=27, null = 'True')
    birthday = models.DateField(null = 'True')
    gender = models.TextField(null = 'True')
    expertise1 = models.TextField(null = 'True')
    expertise2 = models.TextField(null = 'True')
    expertise3 = models.TextField(null = 'True')
    email = models.EmailField(null = 'True')
    description = models.TextField(null = 'True')

add_stats/models.py
from django.db import models

# Create your models here.

add_updatestatus/models.py
from django.db import models
# from django.core.validators import MaxLengthValidator
# Create your models here.

class Status(models.Model):
    description = models.CharField(max_length=250)
    #description = models.TextField(validators=[MaxLengthValidator(300)])
    created_date = models.DateTimeField(auto_now_add=True)

add_friend/forms.py
from django import forms

class Friend_Form(forms.Form):
    error_friends = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL media sosial',
    }
    attrs = {
        'class': 'form-control'
    }

    Name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    URL = forms.URLField(label='URL', required=True, widget=forms.URLInput(attrs=attrs))

add_profile/forms.py
'''
from django import forms

class EditProfileFormLeft(forms.Form):
    error_friends = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan URL media sosial',
    }
    attrs = {
        'class': 'form-control'
    }

    Name = forms.CharField(label='Name', required=True, max_length=27, widget=forms.TextInput(attrs=attrs))
    Birthday = forms.DateField(label="Birthday", required=True, widget=forms.DateInput(attrs=attrs))
    Gender = forms.TypedChoiceField(label="Gender", required=True, widget=forms.Select(attrs=attrs))
    Expertise = forms.ChoiceField(label="Expertise", required=True, widget=forms.Select(attrs=attrs))
    Email = forms.EmailField(label="Email", required=True, widget=forms.EmailInput(attrs=attrs))
    ImageSource = forms.URLField(label='URL', required=False, widget=forms.URLInput(attrs=attrs))

class EditProfileFormRight(forms.Form):
    attrs = {
        'class': 'form-control'
    }

    forms.CharField(label='Description', required=False, widget=forms.Textarea(attrs=description_attrs))
'''

add_updatestatus/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Input required',
    }
    description_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Update your status here...'
    }
    # description_attrs = {
    #     'type': 'text',
    #     'cols': 50,
    #     'rows': 6,
    #     'class': 'status-form-textarea',
    #     'placeholder':'Update your status here...'
    # }

    description = forms.CharField(label='Update Status', required=True, max_length=250, widget=forms.TextInput(attrs=description_attrs))
    # description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

add_friend/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Friend_Form
from .models import Friend

# Create your views here.
response = {}
def index(request):
    html = 'add_friend/add_friend.html'
    response['friend_form'] = Friend_Form
    response['friend'] = Friend.objects.all().order_by('created_date')
    return render (request, html, response)

def add_friend(request):
    form = Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['Name'] = request.POST['Name']
        response['URL'] = request.POST['URL']
        friend=Friend(Name=response['Name'], URL=response['URL'])
        friend.save()
        return HttpResponseRedirect('/add-friend/')
    else:
        return HttpResponseRedirect('/add-friend/')

add_profile/views.py
from django.shortcuts import render
from .models import Identity

# Create your views here.
response = {'author': "DiligentSquad"}
def index(request):
    if Identity.objects.all().count()==0:
        Identity.objects.create(
        name = "Kitty",
        birthday = "1996-1-11",
        gender = "Female",
        expertise1 = "Statistics",
        expertise2 = "Programming",
        expertise3 = "Public Speaking",
        email = "blahblahblah@gmail.com",
        description = "Give me fish"
        )
    identity = Identity.objects.get(id=1)
    response = {
    'name':identity.name,
    'gender':identity.gender,
    'birthday':identity.birthday,
    'email':identity.email,
    'expertise1':identity.expertise1,
    'expertise2':identity.expertise2,
    'expertise3':identity.expertise3,
    'description':identity.description,
    }
    html = "profile.html"
    return render(request, html, response)

add_stats/views.py
from django.shortcuts import render
from add_profile.models import Identity
from add_friend.models import Friend
from add_updatestatus.models import Status


response = {'author': "DiligentSquad"}
def index(request):
	profile = Identity.objects.get(id=1)
	response['name'] = profile.name
	html = 'stats.html'
	response['friends'] = Friend.objects.all().count()
	response['feed'] = Status.objects.all().count()
	response['latestpost'] = Status.objects.latest('id')
	return render(request, html, response)

add_updatestatus/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Status_Form
from .models import Status

# Create your views here.
response = {}

def index(request):
    status = Status.objects.all()
    response['status_list'] = status
    html = 'status.html'
    response['update_status'] = Status_Form
    return render(request, html, response)

def update_status(request):
    form = Status_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        status = Status(description=response['description'])
        status.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

add_friend/templates/add_friend/add_friend.html
{% extends "base.html" %}
{% block content %}
<section name="form">
    <div class="container h-100" style="padding-top: 25px; padding-bottom:50px">
      <nav class="navbar navbar-expand-lg bg-light navbar-light">
        <ul class="navbar-nav">
          <li class="nav-item">
            <font color="black" face="comic sans ms" size="5"> Add Friend </font>
          </li>
        </ul>
      </nav>
        <form id="form" method="POST" action="{% url 'add-friend:add_friend' %}">
            {% csrf_token %}
            {{ friend_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Add Friend" style="margin-top:30px">
            <br>
        </form>
    </div>
</section>

<section name="list">
        <nav aria-label="breadcrumb " style="padding-top:100px">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page">
                      <font color= "black" size="5"> List Friends </font>
                    </li>
                    </ol>
        </nav>
        <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th> Name </th>
                    <th> URL </th>
                    <th> Added Time </th>
                </tr>
            </thead>
                <tbody>

                    {% for i in friend %}
                    <tr class="success">
                        <td> {{i.Name}} </td>
                        <td> <a href="{{i.URL}}">{{i.URL}}</a> </td>
                        <td> {{i.created_date}} </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
    </div>
</section>

{% endblock %}

add_profile/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div class="container h-100" style="padding-top: 25px; padding-bottom:50px">
  <nav class="navbar navbar-expand-lg bg-light navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <font color="black" face="comic sans ms" size="5"> Profile </font>
      </li>
    </ul>
  </nav>
<!--  <div class="float-right" style="margin-top: 10px;">
    <a href="/editprofile/" class="btn btn-info" role="button"><font color="white"> Edit Profile </font></a>
  </div> -->
  <div class="row justify-content-center" style="margin-top: 50px; margin-bottom: 10px;">
    <div class="col-12 text-center">
      <img src="../../static/kucing.jpg" class="rounded-circle" width="200" height="200">
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 text-center">
      <h2> {{name}} </h2>
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top: 30px;">
    <div class="col-1">
    </div>
    <div class="col-2">
      <span class="lead"> Birthday </span>
    </div>
    <div class="col-6"> {{birthday}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top: 10px;">
    <div class="col-1">
    </div>
    <div class="col-2">
      <span class="lead"> Gender </span>
    </div>
    <div class="col-6"> {{gender}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top: 10px;">
    <div class="col-1">
    </div>
    <div class="col-2">
      <span class="lead"> Expertise </span>
    </div>
    <div class="col-6">
      <span class="badge badge-pill badge-secondary"> {{expertise1}} </span>
      <span class="badge badge-pill badge-secondary"> {{expertise2}} </span>
      <span class="badge badge-pill badge-secondary"> {{expertise3}} </span>
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top: 10px;">
    <div class="col-1">
    </div>
    <div class="col-2">
      <span class="lead"> Email </span>
    </div>
    <div class="col-6"> {{email}}
    </div>
  </div>
  <div class="row justify-content-center" style="margin-top: 10px;margin-bottom:40px;">
    <div class="col-1">
    </div>
    <div class="col-2">
      <span class="lead"> Description </span>
    </div>
    <div class="col-6"> {{description}}
    </div>
  </div>
</div>
{% endblock %}

add_stats/templates/stats.html
{% extends "base.html" %}

{% block content %}
<head>
  <title>Statistic</title>
</head>
<body>
  <div class="container h-100" style="padding-top: 25px; padding-bottom:50px">
    <nav class="navbar navbar-expand-lg bg-light navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item">
          <font color="black" face="comic sans ms" size="5"> Statistics </font>
        </li>
      </ul>
    </nav>
    <div class="row justify-content-center" style="margin-top: 50px; margin-bottom: 10px;">
        <div class="col-sm-12 text-center">
          <img src="../../static/kucing.jpg" class="rounded-circle" width="200" height="200">
        </div>
      </div>
      <div class="row justify-content-center">
        <div class="col-sm-12 text-center">
          <h2> {{name}} </h2>
        </div>
      </div>
  	<div class="row justify-content-left">
        <div class="col-sm-6 text-left">
          <h2> Friends : {{friends}} People</h2>
  	  </div>
  	  <div class="col-sm-6 text-center">
  		<h2> Feed : {{feed}} Post</h2>
  	  </div>
  	</div>
  	<div class="row" style="margin-top:10px; margin-left:15px">
  		<h4>Latest Post :</h4>
  	</div>
  	<div class="row" style="margin-top:10px; margin-left:15px">
  		<h6>{{name}}</h6>
  	</div>
  	<div class="row" style="margin-top:5px; margin-left:15px">
  		<p class="mb-0">{{latestpost.description}}</p>
  	</div>
  	<div class="row" style="margin-top:5px; margin-left:15px">
  	    <p class="mb-0">{{latestpost.created_date}}</p>
  	</div>
  </div>
</body>
{% endblock %}

add_updatestatus/templates/status.html
{% extends "base.html" %}

{% block content %}


<div class="container h-100" style="padding-top:25px;padding-bottom:75px">
  <nav class="navbar navbar-expand-lg bg-light navbar-light">
    <ul class="navbar-nav">
      <li class="nav-item">
        <font color="black" face="comic sans ms" size="5"> Status </font>
      </li>
    </ul>
  </nav>
</div>
<section name="status">
<div class="container h-100" style="padding-top:25px;padding-bottom:50px">
  <nav aria-label="breadcrumb " style="padding-top:100px">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">Home </li>
                </ol>
  </nav>
    <form id="form" method="POST" action="{% url 'update-status:update_status' %}">
      {% csrf_token %}
      {{ update_status.as_p }}
      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
    </form>
</div>
</section>

<section name="my-status" id="my-status">
   <div class="container h-100" style="padding-top:25px;padding-bottom:50px">
        <nav aria-label="breadcrumb " style="padding-top:100px">
                 <ol class="breadcrumb">
                    <li class="breadcrumb-item active" aria-current="page"> Recent Status </li>
                    </ol>
        </nav>
            {% for status in status_list %}
                <div class="container-item">
                    <div class="status-list">
                        <div class="status-list-description">
                            <p class="card-text">{{status.description}}</p>
                        </div>
                        <div class="status-list-date-added">
                            {{status.created_date}}
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
</section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1", "shrink-to-fit=no"> <!-- edit -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <title>
        {% block title %} Diligent Squad {% endblock %}
    </title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">DiligentSquad</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/profile/">profile</a>
              </li>
        <li class="nav-item">
                <a class="nav-link" href="/update-status/">status</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="/add-friend/">friends</a>
        </li>
        <li class="nav-item">
                <a class="nav-link" href="/stats/">statistic</a>
      </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
  <footer class="footer">
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "footer.html" %}
        {% endblock %}
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>

templates/footer.html
<div class="text-center bg-dark">
	<span class="text-muted">&copy; DiligentSquad Crew</span>
</div>